### ISSUE TITLE
Prepare Tech Change class

### ISSUE THREAD

**Issue by cecilepompei** [MozillaFoundation/Engagement#10]
Tech Change mHealth Class, given by Cecile, April for 60-90 minutes

> angle on having students (40-50 participants, mainly international organizations) creating an Health app with Webmaker to solve one of their challenge
> link to the course: https://www.techchange.org/online-courses/mhealth-mobile-phones-for-public-health/

Driver: Cecile
Team: @benrito 
Interested: @corinagardner @HPaulJohnson @davidascher 
- [x] Demo video on webmaker (3-5 minutes) to upload on tech change  cc @HPaulJohnson @thisandagain 
- [x] Agree on using for the course the desktop version of webmaker versus mobile for the "students" attending
- [ ] Write a narrative for the class @cecile + @HPaulJohnson + @benrito 
- [ ] Set a KPI for the course @cecile
- [ ] Need a more tech person to be my partner to do 30 min x 2 of answering questions (if questions there was!) + live demo of webmaker for 10 minutes during the class in April
  cc @laurareynal @secretrobotron
- [ ] Prepare a deck on Mozilla @HPaulJohnson @benrito : do we have this?
- [ ] Define the challenge for the course @cecile

**Comment by lauradereynal** [comment]
Hey @cecilepompei 
The only thing that seems unclear to me is : Why do you want to focus on desktop Webmaker ?

**Comment by cecilepompei** [comment]
I don't want anything in particular, I ask product team what they prefer. Mobile better for me!

**Comment by thisandagain** [comment]
I don't understand why we would use the desktop product for this. Can you clarify where that direction is coming from?

**Comment by benrito** [comment]
I think that this was Corina's suggestion. But agree with everyone that mobile is what we should be using. The desktop product is going to change a lot.

@cecilepompei, if you have time recommend watching: https://air.mozilla.org/new-webmaker-tool-prototype/ It'll help explain how we're going to reset the desktop product and why we should hold off on doing anything with Appmaker.

Cheers!
Ben

**Comment by corinagardner** [comment]
I think the reason from my point of view is that it much easier to demo for a virtual class on a desktop screen share rather than trying to show through a webinar on your phone. Also, any students with iPhones will not be able to participate.

And a general question - don't we see the application for desktop webmaker being exactly for this crowd? Is it going to continue to be developed for the NGO workers that do have computers and want to be able to custom build apps for their programs in the field? If so, that is who this class is made up of...

**Comment by corinagardner** [comment]
Hi guys,

I left the comment above yesterday but for some reason it didn't save. I have since watched the call that Ben shared - thanks this is really helpful. While watching this it strikes me that webmaker has really moved away from the mobile tool that was focused on supporting the creation of local content and seems to be sidelining tools that focus on teaching creating mobile content, specifically. It is a bit contradictory to what I feel I spend every day telling partners about what mofo is working toward. 
Onboarding curious people to becoming makers and teaching them the basics of coding is great is not synonymous with creating tools that help people who will never learn to code to create localised content for their community. Maybe I am reading too much into this but it seems one of these missions has been lost a bit in this latest design.

**Comment by lauradereynal** [comment]
Hey Corina, I was writing an answer regarding TechChange. I think we can talk about the design issue you raise in our next meeting. I don't think its that far, and people will still be able to create content, however, we are trying to bring FUN into the product, which was a major feedback from all 3 countries. Right now Webmaker App is boring, both for the creator and the end user. 

TechChange. 
Major  + 1 with : They might all have iPhones - that is a problem. @cecilepompei 

This crowd was one of our "Persona Idea" back in August when we first started, but after the research we did not identify NGO workers with computers as a primary persona for Webmaker. 
In all countries we met NGO workers, and people interested in creating content were mostly young passionate NGO workers, teaching digital literacy, not health, who wanted to share their experience. But "creating an app to solve their challenge" is unlikely to be the reality. 

However, I think its cool to try and demo the app with them. 
Maybe one angle could be : in your daily job, find 2 ideas of how you could use it, either for you or for your network.

**Comment by corinagardner** [comment]
@cecilepompei you may want to circle around with the TechChange guys to get their feedback on this, since the invite to do the course originally came after them seeing the appmaker tool. It is now a slightly different conversation and they might have some suggestions on how to deal with the limitations of webmaker mobile in the webinar format. The limitations being that 1) it is not easy to demo and 2) many people will not be able to play directly.

**Comment by benrito** [comment]
The Learning Products review is tomorrow and I think some of the market-fit and market strategy stuff will come up.

Agree that we need to better understand some of the pivot thinking with respect to the product. In the end I hope/expect it won't change our story too much.

**Comment by cecilepompei** [comment]
Hi All,

I am going to try and push for only a presentation on Mofo and Webmaker (mobile) for this class, where the students make an app using webmaker (they will probably try and do something Health, but doesnt have to be)

I have a few question for the team though to help me
- Do we have a deck presentation on Mofo? @HPaulJohnson  @benrito 
- Do we have a little manual on how to use Webmaker mobile? @secretrobotron 
- and maybe is it a problem if we test the current version on webmaker mobile? @thisandagain 

It is only 60 minutes so I just have to present Mofo and Webmaker for 30 min and then answer questions for 30 min. It should be worth it !

**Comment by secretrobotron** [comment]
- There are a couple quick gifs on the homepage that show what Webmaker App does: https://webmaker.org/app
- The script we used for MWC which shows motivations for the app and how to use it: https://docs.google.com/a/mozillafoundation.org/presentation/d/16fOMRKqvbDl_UknsdN8EFTX9iB18iWd8FpaTFvfqjqg/edit#slide=id.g61fa25a70_037 (might fulfill what you need for a MoFo preso as well)
