### ISSUE TITLE
Finalize the Fox Den presentation

### ISSUE THREAD

**Issue by benrito** [MozillaFoundation/Engagement#2]
For MWC. @HPaulJohnson @davidascher @cecilepompei @amirad

**Comment by benrito** [comment]
https://www.dropbox.com/s/k6oxzcm5jbdbil4/DRAFT_Local_content_literacy_MWC2015.pdf?dl=0

**Comment by benrito** [comment]
Feedback please!

**Comment by davidascher** [comment]
Web journey graphic needs restyling.  In general, needs a bunch of typographic work.  Is that scheduled for later?

slide 15: let's not use a circle that forces the URL to be broken

Souktel logo is way too low-res.

**Comment by HPaulJohnson** [comment]
Overall, looks really nice. 

Slide 4: Think we could have a more exciting visual representation of Webmaker and our value proposition. I will come up with an alternative image. 

Slide 33: As I mentioned to you this is the $ slide. Visually I wish it was more interesting and popped a little more given it's importance. 

I need to give you a new picture of myself also (as I'm way too low-res).

**Comment by HPaulJohnson** [comment]
Some additional feedback/notes relaying from a meeting with Pete this morning: 
- Slideshow theme is for FFOS. Might want to use general Mozilla theme instead. Not a huge deal.
- Add your job title to slide1
- Capitalize "Web" on slide 2
- Start with the problem statement: Access isn't enough and current mobile ecosystem doesn't invite empowerment or participation. 
- Overall, reduce the number of slides if possible. 
- Pete also noted, that we will only be running these sessions Monday-Wednesday (no Thursday Foxden). 

A few additional comments from me: 
- For slide 5, I'd suggest using a nice big screenshot of latest App home screen screen instead of desktop version. Alternatively, you could even use screenshot of webmaker.org/mentor; it's not perfect in that it's more mentor-focused but as a visual it's much more interesting than what you currently have and conveys digital skill building better. 
- I don't understand purpose of MDN slide. Might make sense in context of what you are going to be talking about but I'd like to focus/reinforce a single URL throughout this presentation and that URL should be webmaker.org/localweb

**Comment by benrito** [comment]
from @APLSmith

Slide 9: source should be w3techs, Ethnologue and GSMA
Slide 19: Missing a trick by not listing all communities that are localising? Graphic?

**Comment by edrushka** [comment]
Closing as MWC is now over.
